/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-08-01 06:32:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_005fout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/mypage/../footer1.jsp", Long.valueOf(1564556209381L));
    _jspx_dependants.put("/WEB-INF/mypage/../footer2.jsp", Long.valueOf(1564556209382L));
    _jspx_dependants.put("/WEB-INF/mypage/../header1.jsp", Long.valueOf(1564556209382L));
    _jspx_dependants.put("jar:file:/D:/project_bbb/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MovieProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1564550655296L));
    _jspx_dependants.put("/WEB-INF/mypage/../header2.jsp", Long.valueOf(1564638657900L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!--\r\n");
      out.write("/**\r\n");
      out.write("* @Class Name : member_out.jsp\r\n");
      out.write("* @Description : 회원 탈퇴\r\n");
      out.write("* @Modification Information\r\n");
      out.write("* @\r\n");
      out.write("* @  수정일                수정자                  수정내용\r\n");
      out.write("* @ ---------   ---------   -------------------------------\r\n");
      out.write("* @ 2019.07.06         황진석                최초생성\r\n");
      out.write("* @author bit 2조\r\n");
      out.write("* @since 2019. 07.01\r\n");
      out.write("* @version 1.0\r\n");
      out.write("* @see\r\n");
      out.write("*\r\n");
      out.write("*  Copyright (C) by Biㅁt All right reserved.\r\n");
      out.write("*/\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- header1 시작 -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if IE 7]>\r\n");
      out.write("<html class=\"ie ie7 no-js\" lang=\"en-US\">\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<!--[if IE 8]>\r\n");
      out.write("<html class=\"ie ie8 no-js\" lang=\"en-US\">\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<!--[if !(IE 7) | !(IE 8)  ]><!-->\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Basic need -->\r\n");
      out.write("<title>BlockBuster</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<link rel=\"profile\" href=\"#\">\r\n");
      out.write("\r\n");
      out.write("<!--Google Font-->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href='http://fonts.googleapis.com/css?family=Dosis:400,700,500|Nunito:300,400,600' />\r\n");
      out.write("<!-- Mobile specific meta -->\r\n");
      out.write("<meta name=viewport content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"format-detection\" content=\"telephone-no\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS files -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<!-- hm | </head>  전까지 -->\r\n");
      out.write("<!--  하단에 css 링크 추가 -->\r\n");
      out.write("<!-- header1 끝 -->");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<!-- header2 시작 -->\r\n");
      out.write("<!--  hm | </head> 부터 </header>까지 -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   <!--preloading-->\r\n");
      out.write("   <div id=\"preloader\">\r\n");
      out.write("      <img class=\"logo\" src=\"resources/images/logo1.png\" alt=\"\" width=\"119\"\r\n");
      out.write("         height=\"58\">\r\n");
      out.write("      <div id=\"status\">\r\n");
      out.write("         <span></span> <span></span>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!--end of preloading-->\r\n");
      out.write("\r\n");
      out.write("   <!-- ======================================================                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ================================================================== -->\r\n");
      out.write("   <!--                                               hm |        모달 팝업 시작                                                  -->\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("   <!--                                            hm |         로그인 팝업 시작                                                  -->\r\n");
      out.write("   <!-- 입력 폼 패턴 삭제 -->\r\n");
      out.write("   <div class=\"login-wrapper\" id=\"login-content\">\r\n");
      out.write("      <div class=\"login-content\">\r\n");
      out.write("         <a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("         <h3>Login</h3>\r\n");
      out.write("         <form action=\"Login\" method=\"post\" name=\"LoginForm\">\r\n");
      out.write("            <!-- action 변경 필요 -->\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label for=\"email\"> <input type=\"text\" name=\"m_email\"\r\n");
      out.write("                  id=\"m_email\" placeholder=\"이메일을 입력하세요\" required=\"required\"\r\n");
      out.write("                  autocapitalize=\"off\" />\r\n");
      out.write("               </label>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label for=\"password\"> <input type=\"password\"\r\n");
      out.write("                  name=\"m_password\" id=\"m_password\" placeholder=\"비밀번호를 입력하세요\"\r\n");
      out.write("                  required=\"required\" />\r\n");
      out.write("               </label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"remember\">\r\n");
      out.write("                  <div>\r\n");
      out.write("                     <input type=\"checkbox\" id=\"idSaveCheck\" name=\"remember\"\r\n");
      out.write("                        value=\"Remember me\"><span>아이디 저장</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row hm_logtext\">\r\n");
      out.write("               <button type=\"button\" id=\"loginbtn\">Login</button>\r\n");
      out.write("               <a class=\"btn signupLink\" href=\"#\">회원가입 | </a> <a\r\n");
      out.write("                  class=\"btn idfindLink\" href=\"\">아이디 찾기 | </a> <a\r\n");
      out.write("                  class=\"btn pwfindLink\" href=\"\">비밀번호 찾기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("         </form>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!--    hm |                                                         로그인 폼 팝업 끝                                                 -->\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("   <!-- |   hm |                                                      아이디 찾기 팝업 시작                                              | -->\r\n");
      out.write("   <div class=\"login-wrapper\" id=\"id-find-content\">\r\n");
      out.write("      <!-- login-content 아이디 변경 -->\r\n");
      out.write("      <div class=\"login-content\">\r\n");
      out.write("         <!-- login-content 클래스 변경 X -->\r\n");
      out.write("         <a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("         <h3>아이디 찾기</h3>\r\n");
      out.write("         <h6>등록된 휴대폰 번호로 찾기</h6>\r\n");
      out.write("         <p>가입 당시 입력한 휴대전화 번호를 통해 아이디를 찾을 수 있습니다.</p>\r\n");
      out.write("         <form method=\"post\" class=\"findIdClass\">\r\n");
      out.write("            <!-- login.php 액션 변경 -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label for=\"username\"> <!-- username 라벨 이름 변경 --> 이름 <!-- 라벨 추가 -->\r\n");
      out.write("                  <input type=\"text\" name=\"m_name\" id=\"id_username\" placeholder=\"이름\"\r\n");
      out.write("                  required=\"required\" autocapitalize=\"off\" /> <!-- name, id, placeholder 변경-->\r\n");
      out.write("               </label>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row phone\">\r\n");
      out.write("               <label for=\"phone\"> <!-- password 라벨 이름 변경 --> 휴대전화</br> <!-- 라벨 추가 -->\r\n");
      out.write("                  <input type=\"text\" name=\"m_phone1\" maxlength=\"3\" placeholder=\"\"\r\n");
      out.write("                  required=\"required\" /> - <input type=\"text\" name=\"m_phone2\"\r\n");
      out.write("                  maxlength=\"4\" placeholder=\"\" required=\"required\" /> - <input\r\n");
      out.write("                  type=\"text\" name=\"m_phone3\" maxlength=\"4\" placeholder=\"\"\r\n");
      out.write("                  required=\"required\" /> <!-- name, id, placeholder 변경-->\r\n");
      out.write("               </label>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\" id=\"hm_logtext\">\r\n");
      out.write("               <!-- <button type=\"submit\">확인</button>  버튼 이름 변경 -->\r\n");
      out.write("               <button class=\"idokLink\" type=\"button\">확인</button>\r\n");
      out.write("               <a class=\"btn pwfindLink\" href=\"\">비밀번호 찾기</a>\r\n");
      out.write("               <!-- 하단 링크 변경 -->\r\n");
      out.write("            </div>\r\n");
      out.write("         </form>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- |        hm |                                                  아이디 찾기 팝업 끝                                              |  -->\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("   <!-- |        hm |                                            아이디 찾기 확인 팝업 시작                                              | -->\r\n");
      out.write("   <div class=\"login-wrapper\" id=\"id-ok-content\">\r\n");
      out.write("      <!-- login-content 아이디 변경 -->\r\n");
      out.write("      <div class=\"login-content\" style=\"text-align: center\">\r\n");
      out.write("         <!-- login-content 클래스 변경 X -->\r\n");
      out.write("         <a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("         <!--  \r\n");
      out.write("            <h6 class=\"h6one\"> 입력하신 정보와 일치하는 아이디는 <br>아래와 같습니다.</h6>\r\n");
      out.write("         <h6 class=\"h6two\"style=\"display:none\"> 입력하신 정보와 일치하는 <br>아이디가 없습니다.</h6>\r\n");
      out.write("         -->\r\n");
      out.write("         <!-- 이메일 정보 추가 -->\r\n");
      out.write("         <p>\r\n");
      out.write("            <span> </span>\r\n");
      out.write("         </p>\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <button class=\"close\" type=\"button\" style=\"display: inline-block;\">확인</button>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- |           hm |                                          아이디 찾기 확인 팝업 끝                                              |  -->\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("   <!-- |          hm |                                        비밀번호 찾기 폼 팝업 시작                                              | -->\r\n");
      out.write("   <div class=\"login-wrapper\" id=\"pw-find-content\">\r\n");
      out.write("      <!-- login-content 아이디 변경 -->\r\n");
      out.write("      <div class=\"login-content\">\r\n");
      out.write("         <!-- login-content 클래스 변경 X -->\r\n");
      out.write("         <a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("         <h3>비밀번호 찾기</h3>\r\n");
      out.write("         <h6>등록된 휴대폰 번호로 찾기</h6>\r\n");
      out.write("         <p>가입 당시 입력한 휴대전화 번호를 통해 인증 후 새비밀번호를 등록해주세요.</p>\r\n");
      out.write("         <form method=\"post\" class=\"findPwClass\">\r\n");
      out.write("            <!-- login.php 액션 변경 -->\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label for=\"email\"> <!-- username 라벨 이름 변경 --> 이메일 <!-- 라벨 추가 -->\r\n");
      out.write("                  <input type=\"text\" name=\"m_email\" id=\"pw_email\" placeholder=\"이메일\"\r\n");
      out.write("                  required=\"required\" autocapitalize=\"off\" /> <!-- name, id, placeholder 변경-->\r\n");
      out.write("               </label>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label for=\"username\"> <!-- username 라벨 이름 변경 --> 이름 <!-- 라벨 추가 -->\r\n");
      out.write("                  <input type=\"text\" name=\"m_name\" id=\"pw_username\" placeholder=\"이름\"\r\n");
      out.write("                  required=\"required\" autocapitalize=\"off\" /> <!-- name, id, placeholder 변경-->\r\n");
      out.write("               </label>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row phone\">\r\n");
      out.write("               <label for=\"phone\"> <!-- password 라벨 이름 변경 --> 휴대전화</br> <!-- 라벨 추가 -->\r\n");
      out.write("                  <!-- 라벨 추가 --> <input type=\"text\" name=\"m_phone1\" maxlength=\"3\"\r\n");
      out.write("                  placeholder=\"\" required=\"required\" /> - <input type=\"text\"\r\n");
      out.write("                  name=\"m_phone2\" maxlength=\"4\" placeholder=\"\" required=\"required\" />\r\n");
      out.write("                  - <input type=\"text\" name=\"m_phone3\" maxlength=\"4\" placeholder=\"\"\r\n");
      out.write("                  required=\"required\" /> <!-- name, id, placeholder 변경-->\r\n");
      out.write("               </label>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\" id=\"hm_logtext\">\r\n");
      out.write("               <!-- <button type=\"submit\">확인</button>  버튼 이름 변경 -->\r\n");
      out.write("               <button class=\"pwokLink\" type=\"button\">확인</button>\r\n");
      out.write("               <a class=\"btn idfindLink\" href=\"\">아이디 찾기</a>\r\n");
      out.write("               <!-- 하단 링크 변경 -->\r\n");
      out.write("            </div>\r\n");
      out.write("         </form>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- |      hm |                                            비밀번호 찾기 폼 팝업 끝                                               |  -->\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("   <!-- |       hm |                                           비밀번호 찾기 확인 팝업 시작                                              | -->\r\n");
      out.write("   <div class=\"login-wrapper\" id=\"pw-ok-content\">\r\n");
      out.write("      <!-- login-content 아이디 변경 -->\r\n");
      out.write("      <div class=\"login-content\">\r\n");
      out.write("         <!-- login-content 클래스 변경 X -->\r\n");
      out.write("         <a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("         <h3>비밀번호 찾기</h3>\r\n");
      out.write("         <p>회원님의 계정 비밀번호를 재설정 해주세요.</p>\r\n");
      out.write("         <p>신규비밀번호는 8-20자 이내의 영문자, 숫자의 조합으로 작성 하셔야 합니다.</p>\r\n");
      out.write("         <form class=\"newPassword\">\r\n");
      out.write("            <input type=\"hidden\" id=\"phone_number\" name=\"m_phone\" value=\"\" />\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label for=\"password\"> <!-- username 라벨 이름 변경 --> 신규 비밀번호\r\n");
      out.write("                  입력 </br> <!-- 라벨 추가 --> <input type=\"password\" name=\"m_password\"\r\n");
      out.write("                  id=\"password\" placeholder=\"\" required=\"required\"\r\n");
      out.write("                  autocapitalize=\"off\" onchange=\"checkPassword(this.value)\" /> <!-- name, id, placeholder 변경-->\r\n");
      out.write("                  <span> </span>\r\n");
      out.write("               </label>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label for=\"password2\"> <!-- username 라벨 이름 변경 --> 비밀번호 확인\r\n");
      out.write("                  </br> <!-- 라벨 추가 --> <input type=\"password\" name=\"m_password2\"\r\n");
      out.write("                  id=\"password2\" placeholder=\"\" required=\"required\"\r\n");
      out.write("                  autocapitalize=\"off\" onchange=\"checkPasswordConfirm(this.value)\" />\r\n");
      out.write("                  <!-- name, id, placeholder 변경--> <span> </span>\r\n");
      out.write("               </label>\r\n");
      out.write("               <div class=\"alert-success\" id=\"alert-success\">비밀번호가 일치합니다.</div>\r\n");
      out.write("               <div class=\"alert-danger\" id=\"alert-danger\">비밀번호가 일치하지 않습니다.</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <button class=\"pwcfLink\" type=\"button\">비밀번호 변경</button>\r\n");
      out.write("            </div>\r\n");
      out.write("         </form>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- |     hm |                                             비밀번호 찾기 확인 팝업 끝                                               |  -->\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("   <!--         hm |                                                   회원가입 폼 팝업 시작                                              -->\r\n");
      out.write("   <!--signup form popup-->\r\n");
      out.write("   <div class=\"login-wrapper\" id=\"signup-content\">\r\n");
      out.write("      <div class=\"login-content\">\r\n");
      out.write("         <a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("         <h3>sign up</h3>\r\n");
      out.write("         <form method=\"post\" id=\"joinform\" action=\"memberJoin\"\r\n");
      out.write("            method=\"post\" onsubmit=\"return ws_check()\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("               <label for=\"email-2\"> 이메일 :</br> \r\n");
      out.write("               <input type=\"text\" name=\"m_email\" id=\"email-2\" placeholder=\"이메일을 입력하세요\" required=\"required\" />\r\n");
      out.write("               <button id=\"email_overlap_chk\" class=\"overch\" style=\"width:19%;\" >중복확인</button>\r\n");
      out.write("               <div id=\"email_chk_msg\">이메일 중복검사를 눌러주세요</div>   \r\n");
      out.write("\r\n");
      out.write("               </label>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label for=\"username-2\"> 이름 : <input type=\"text\"\r\n");
      out.write("                  name=\"m_name\" id=\"username-2\" placeholder=\"이름을 입력하세요\"\r\n");
      out.write("                  />\r\n");
      out.write("               </label>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label for=\"nickname-2\"> 닉네임 :</br> <input type=\"text\"\r\n");
      out.write("                  name=\"m_nickname\" id=\"nickname-2\" placeholder=\"닉네임을 입력하세요\"\r\n");
      out.write("                  required=\"required\" />\r\n");
      out.write("                  <button id=\"nick_overlap_chk\" style=\"width:19%;\">중복확인</button>\r\n");
      out.write("                  <div id=\"nick_chk_msg\">닉네임 중복검사를 눌러주세요</div>\r\n");
      out.write("               </label>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label for=\"password-2\"> 비밀번호: <input type=\"password\"\r\n");
      out.write("                  name=\"m_password\" id=\"password-2\"\r\n");
      out.write("                  placeholder=\"8-20자 이내 영문자, 숫자의 조합\" required=\"required\" />\r\n");
      out.write("               </label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label for=\"repassword-2\"> 비밀번호 확인 : <input type=\"password\"\r\n");
      out.write("                  name=\"password\" id=\"repassword-2\"\r\n");
      out.write("                  placeholder=\"8-20자 이내 영문자, 숫자의 조합\" Srequired=\"required\" />\r\n");
      out.write("               </label>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row phone\">\r\n");
      out.write("               <label for=\"repassword-2\"> 휴대전화 : </br> <input type=\"text\"\r\n");
      out.write("                  name=\"m_phone1\" placeholder=\"\" Srequired=\"required\" /> - <input\r\n");
      out.write("                  type=\"text\" name=\"m_phone2\" placeholder=\"\" Srequired=\"required\" />\r\n");
      out.write("                  - <input type=\"text\" name=\"m_phone3\" placeholder=\"\"\r\n");
      out.write("                  Srequired=\"required\" />\r\n");
      out.write("               </label>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <label for=\"genre-2\"> 선호장르 : </br> <label\r\n");
      out.write("                  class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("                     name=\"m_favorite\" value=\"공포/호러\" type=\"radio\" checked><span><i></i>공포/호러</span>\r\n");
      out.write("               </label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("                     name=\"gender4\" value=\"멜로/로맨스\" type=\"radio\"><span><i></i>멜로/로맨스\r\n");
      out.write("                  </span>\r\n");
      out.write("               </label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("                     name=\"m_favorite\" value=\"액션\" type=\"radio\"><span><i></i>액션</span>\r\n");
      out.write("               </label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("                     name=\"m_favorite\" value=\"코미디\" type=\"radio\"><span><i></i>코미디</span>\r\n");
      out.write("               </label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("                     name=\"m_favorite\" value=\"범죄\" type=\"radio\"><span><i></i>범죄</span>\r\n");
      out.write("               </label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("                     name=\"m_favorite\" value=\"스릴러\" type=\"radio\"><span><i></i>스릴러</span>\r\n");
      out.write("               </label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("                     name=\"m_favorite\" value=\"느와르\" type=\"radio\"><span><i></i>느와르</span>\r\n");
      out.write("               </label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("                     name=\"m_favorite\" value=\"가족\" type=\"radio\"><span><i></i>가족</span>\r\n");
      out.write("               </label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("                     name=\"m_favorite\" value=\"애니메이션\" type=\"radio\"><span><i></i>애니메이션</span>\r\n");
      out.write("               </label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("                     name=\"m_favorite\" value=\"코미디\" type=\"radio\"><span><i></i>코미디</span>\r\n");
      out.write("               </label>\r\n");
      out.write("               </label>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <label for=\"terms-2\"> 약관동의 : </br> <label\r\n");
      out.write("                  class=\"fancy-checkbox custom-bgcolor-coral\"> <input\r\n");
      out.write("                     type=\"checkbox\" checked name=\"useage_agree\" value=\"usage_ok\"><span>[필수]이용약관</span>\r\n");
      out.write("               </label> <a class=\"termsLink\">약관보기</a> <label\r\n");
      out.write("                  class=\"fancy-checkbox custom-bgcolor-coral\"> <input\r\n");
      out.write("                     type=\"checkbox\" checked name=\"info_agree\" value=\"info_ok\"><span>[필수]개인정보\r\n");
      out.write("                        수집 및 이용</span>\r\n");
      out.write("               </label> <a class=\"termsLink\">약관보기</a> <input name=\"m_cert\" type=\"hidden\"\r\n");
      out.write("                  value=\"Y\" /> <label class=\"fancy-checkbox custom-bgcolor-coral\">\r\n");
      out.write("                     <input type=\"checkbox\" checked name=\"m_eagree\" value=\"Y\"><span>이메일\r\n");
      out.write("                        수신 동의</span>\r\n");
      out.write("               </label> <label class=\"fancy-checkbox custom-bgcolor-coral\"> <input\r\n");
      out.write("                     type=\"checkbox\" checked name=\"m_sagree\" value=\"Y\"><span>SMS\r\n");
      out.write("                        수신 동의</span>\r\n");
      out.write("               </label>\r\n");
      out.write("               </label> <label class=\"fancy-checkbox custom-bgcolor-coral\" id=\"checkall\">\r\n");
      out.write("                  <input type=\"checkbox\" checked><span>전체동의</span>\r\n");
      out.write("\r\n");
      out.write("               </label>\r\n");
      out.write("               <hr>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <button class=\"signupokLink\" type=\"submit\">가입하기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("         </form>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!--end of signup form popup-->\r\n");
      out.write("   <!--        hm |                                                     회원가입 폼 팝업 끝                                               -->\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("   <!-- |      hm |                                              회원가입 확인 팝업 시작                                                 | -->\r\n");
      out.write("   <!--signup OK popup-->\r\n");
      out.write("   <div class=\"login-wrapper\" id=\"signup-ok-content\" style=\"height: 50%;\">\r\n");
      out.write("      <div class=\"login-content\">\r\n");
      out.write("         <a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("         <h3>sign up</h3>\r\n");
      out.write("\r\n");
      out.write("         <h4>회원가입이 완료되었습니다.</h4>\r\n");
      out.write("         </br>\r\n");
      out.write("         <!-- 코드수정: id 넣어야 함-->\r\n");
      out.write("         <h6>회원님 회원가입을 축하합니다.</h6>\r\n");
      out.write("         </br>\r\n");
      out.write("         <p>블록버스터의 다양한 영화 정보를 확인하세요!</p>\r\n");
      out.write("\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <button class=\"close\" type=\"submit\" id=\"hm_button2\">홈으로</button>\r\n");
      out.write("            <button class=\"loginLink\" type=\"submit\" id=\"hm_button2\">로그인</button>\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!--end of signup OK popup-->\r\n");
      out.write("   <!-- |          hm |                                           회원가입 확인 팝업 끝                                                 |  -->\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("   <!-- |          hm |                                          아이디 중복확인 팝업 시작                                               | -->\r\n");
      out.write("   <div class=\"login-wrapper\" id=\"id-check-content\">\r\n");
      out.write("      <!-- login-content 아이디 변경 -->\r\n");
      out.write("      <div class=\"login-content\">\r\n");
      out.write("         <!-- login-content 클래스 변경 X -->\r\n");
      out.write("         <a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("         <h3>아이디 중복 확인</h3>\r\n");
      out.write("\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <label for=\"email\"> <!-- username 라벨 이름 변경 --> 사용할 이메일 입력 <!-- 라벨 추가 -->\r\n");
      out.write("               <input type=\"text\" name=\"email\" id=\"email\" placeholder=\"\"\r\n");
      out.write("               required=\"required\" autocapitalize=\"off\" /> <!-- name, id, placeholder 변경-->\r\n");
      out.write("            </label>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <button class=\"\" type=\"submit\">확인</button>\r\n");
      out.write("            <!-- 한칸만 끄기.. -->\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- |           hm |                                          아이디 중복확인 팝업 끝                                               |  -->\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("   <!-- |            hm |                                        닉네임 중복확인 팝업 시작                                               | -->\r\n");
      out.write("   <div class=\"login-wrapper\" id=\"nik-check-content\">\r\n");
      out.write("      <!-- login-content 아이디 변경 -->\r\n");
      out.write("      <div class=\"login-content\">\r\n");
      out.write("         <!-- login-content 클래스 변경 X -->\r\n");
      out.write("         <a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("         <h3>닉네임 중복 확인</h3>\r\n");
      out.write("\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <label for=\"nickname\"> <!-- username 라벨 이름 변경 --> 사용할 닉네임 입력\r\n");
      out.write("               <!-- 라벨 추가 --> <input type=\"text\" name=\"nickname\" id=\"nickname\"\r\n");
      out.write("               placeholder=\"\" required=\"required\" autocapitalize=\"off\" /> <!-- name, id, placeholder 변경-->\r\n");
      out.write("            </label>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <button class=\"\" type=\"submit\">확인</button>\r\n");
      out.write("            <!-- 한칸만 끄기 -->\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- |      hm |                                               닉네임 중복확인 팝업 끝                                               |  -->\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("   <!-- |            hm |                                        약관 팝업 시작                                               | -->\r\n");
      out.write("   <div class=\"login-wrapper2\" id=\"terms-content\">\r\n");
      out.write("      <!-- login-content 아이디 변경 -->\r\n");
      out.write("      <div class=\"login-content2\">\r\n");
      out.write("         <!-- login-content 클래스 변경 X -->\r\n");
      out.write("         <a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("         <h3>약관</h3>\r\n");
      out.write("         <div class=\"hm_contents\">\r\n");
      out.write("            <h3>제 1장 총칙</h3>\r\n");
      out.write("            <h4>제 1 조 (목적)</h4>\r\n");
      out.write("            <p>본 약관은 통계청(이하 ‘제공기관’이라 한다)에서 제공하는 BBB(Block Buster Bit)를 활용함에\r\n");
      out.write("               있어 준수하여야 하는 활용조건 및 절차, 활용자의 권리・의무 및 책임사항, 기타 필요한 사항을 규정함을 목적으로 합니다.</p>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <!-- <button onclick=\"this.parentNode.parentsNode.style.display = 'none';\">확인</button>-->\r\n");
      out.write("            <button class=\"terms-content-bt\">닫기</button>\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- |      hm |                                               약관 팝업 끝                                               |  -->\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("   <!--        hm |                                                       모달 팝업 끝                                                    -->\r\n");
      out.write("   <!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("   <!-- BEGIN | Header -->\r\n");
      out.write("   <header class=\"ht-header sticky\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <nav class=\"navbar navbar-default navbar-custom\">\r\n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("            <div class=\"navbar-header logo\">\r\n");
      out.write("               <div class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("                  data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("                  <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                  <div id=\"nav-icon1\">\r\n");
      out.write("                     <span></span> <span></span> <span></span>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <a href=\"index\"><img class=\"logo\"\r\n");
      out.write("                  src=\"resources/images/logo1.png\" alt=\"\" width=\"119\" height=\"58\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("            <div class=\"collapse navbar-collapse flex-parent\"\r\n");
      out.write("               id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("               <ul class=\"nav navbar-nav flex-child-menu menu-left\">\r\n");
      out.write("                  <li class=\"hidden\"><a href=\"#page-top\"></a></li>\r\n");
      out.write("                  <!--  hm |   add : 각 항목의 텍스트 변경-->\r\n");
      out.write("                  <li class=\"dropdown first\"><a\r\n");
      out.write("                     class=\"btn btn-default dropdown-toggle lv1\"\r\n");
      out.write("                     href=\"movieTicketing\"> 예매 </a></li>\r\n");
      out.write("                  <li class=\"dropdown first\"><a\r\n");
      out.write("                     class=\"btn btn-default dropdown-toggle lv1\" href=\"movieList\">\r\n");
      out.write("                                             영화 </a></li>\r\n");
      out.write("\r\n");
      out.write("                  <li class=\"dropdown first\"><a\r\n");
      out.write("                     class=\"btn btn-default dropdown-toggle lv1\"\r\n");
      out.write("                     href=\"cinemaList\"> 영화관 </a></li>\r\n");
      out.write("                  <li class=\"dropdown first\"><a\r\n");
      out.write("                     class=\"btn btn-default dropdown-toggle lv1\"\r\n");
      out.write("                     href=\"boardEventCollection\"> 이벤트 & 정보 </a></li>\r\n");
      out.write("                  <li class=\"dropdown first\"><a\r\n");
      out.write("                     class=\"btn btn-default dropdown-toggle lv1\"\r\n");
      out.write("                     data-toggle=\"dropdown\" data-hover=\"dropdown\"> 커뮤니티<i\r\n");
      out.write("                        class=\"fa fa-angle-down\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  </a>\r\n");
      out.write("                     <ul class=\"dropdown-menu level1\">\r\n");
      out.write("                        <li><a href=\"boardFreeListP\">자유 게시판</a></li>\r\n");
      out.write("                        <li class=\"it-last\"><a href=\"boardShareListP\">나눔 게시판</a></li>\r\n");
      out.write("                     </ul></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("               <ul class=\"nav navbar-nav flex-child-menu menu-right\">\r\n");
      out.write("\r\n");
      out.write("                  ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 검색 모달 -->\r\n");
      out.write("            <form id=\"demo-2\">\r\n");
      out.write("               <input type=\"search\" placeholder=\"Search\">\r\n");
      out.write("            </form>\r\n");
      out.write("         </nav>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </header>\r\n");
      out.write("   <!-- END | Header -->\r\n");
      out.write("   <script src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$('#check_all').on('click', function() {\r\n");
      out.write("   //모든 이벤트가 작동이 안되는듯 하다. 페이지 내부에서는 작동. hn_js.js에서는 동일 코드가 미작동. 왜??\r\n");
      out.write("   alert('asdasd');\r\n");
      out.write("   if($('#check_all').is(':checked')) {      $('.chk_box').prop('checked', true);\r\n");
      out.write("   }else {\r\n");
      out.write("      $('.chk_box').prop('checked', false);\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>   \r\n");
      out.write("<!-- header2 끝 -->");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("   \r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("/* 회원탈퇴 클릭 js  */\r\n");
      out.write("var delete_confirm = function ()\r\n");
      out.write("{\r\n");
      out.write("   var deleteyn = confirm('정말 탈퇴하시겠습니까?');\r\n");
      out.write("    if (deleteyn == true) {\r\n");
      out.write("       // yes\r\n");
      out.write("      alert(\"탈퇴가 완료되었습니다.\");\r\n");
      out.write("       location.href = \"/member_delete\";\r\n");
      out.write("    } else {\r\n");
      out.write("       // no\r\n");
      out.write("       \r\n");
      out.write("       return false;\r\n");
      out.write("         \r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div style=\"height:5%;\"></div>\r\n");
      out.write("<div class=\"buster-light\">\r\n");
      out.write("   <div class=\"page-single\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <div class=\"row ipad-width2\">\r\n");
      out.write("            <div class=\"col-md-3 col-sm-12 col-xs-12\">\r\n");
      out.write("                  <div class=\"info\">\r\n");
      out.write("                     <h2> <strong>황진석 님</strong> </h2>\r\n");
      out.write("                     <h3> <strong>h10046245h@naver.com</strong></h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("               <div class=\"user-information-hjs\">\r\n");
      out.write("                     <div class=\"user-fav\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li><a href=\"mypage.do\">마이페이지</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                              \r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li>회원 정보</li>\r\n");
      out.write("                           <li><a href=\"pw_confirm.do\">&nbsp;&nbsp;&nbsp;&nbsp;회원정보수정</a></li>\r\n");
      out.write("                           <li><a href=\"member_out.do\">&nbsp;&nbsp;&nbsp;&nbsp;회원탈퇴</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("               \r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li>고객센터</li>\r\n");
      out.write("                           <li><a href=\"one_list.do\">&nbsp;&nbsp;&nbsp;&nbsp;1:1 문의내역</a></li>\r\n");
      out.write("                           <li><a href=\"faq.do\">&nbsp;&nbsp;&nbsp;&nbsp;FAQ</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-9 col-sm-12 col-xs-12\">\r\n");
      out.write("               <div class=\"tal_info\">\r\n");
      out.write("                  <h1><strong> 회원 탈퇴 </strong></h1>\r\n");
      out.write("               </div>\r\n");
      out.write("                  \r\n");
      out.write("               <div class=\"etcWrap\">\r\n");
      out.write("                  <dl class=\"secedeInfo\">\r\n");
      out.write("                     <dt class=\"tal_info\"><strong>회원탈퇴를 신청하기 전에 안내 사항을 꼭 확인해주세요.</strong></dt>\r\n");
      out.write("                     <dt class=\"b\">회원 탈퇴는 회원님 스스로 신청하시는 것을 원칙으로 합니다.</dt>\r\n");
      out.write("                     <dd>아이디 및 비밀번호 재확인 후 탈퇴 하실 수 있습니다.<br>\r\n");
      out.write("                        만약 로그인이 되지 않아 탈퇴 신청을 할 수 없는 경우에는 1:1문의로\r\n");
      out.write("                        연락 주시기 바랍니다.<br><br>\r\n");
      out.write("                     </dd>\r\n");
      out.write("                           \r\n");
      out.write("                     <dt class=\"b\">회원탈퇴 이후 개인정보 보유사유 및 기간</dt>\r\n");
      out.write("                     <dd>\r\n");
      out.write("                         원칙적으로, 개인정보 수집 및 이용목적이 달성된 후에는 해당 정보를 지체 없이 파기합니다. <br>\r\n");
      out.write("                         단, 다음의 정보에 대해서는 아래의 이유로 명시한 기간 동안 보존합니다.<br>\r\n");
      out.write("                           - 보존 항목 : 로그인ID<br>\r\n");
      out.write("                           - 보존 근거 : 컨텐츠 이용ID 중복방지<br>\r\n");
      out.write("                           - 보존 기간 : 3개월<br>\r\n");
      out.write("                           <br>\r\n");
      out.write("                           - 보존 항목 : 본인인증값<br>\r\n");
      out.write("                           - 보존 근거 : 악용목적에 의한 가입 및 탈퇴방지<br>\r\n");
      out.write("                           - 보존 기간 : 탈퇴일로 3일<br>\r\n");
      out.write("                           <br>\r\n");
      out.write("                           - 보존 항목 : 부정이용 기록<br>\r\n");
      out.write("                           - 보존 근거 : 부정방지 이용<br>\r\n");
      out.write("                           - 보존 기간 : 1년<br>\r\n");
      out.write("                           <br>\r\n");
      out.write("                            그리고 관계법령의 규정에 의하여 보존할 필요가 있는 경우 회사는 <br>아래와 같이 관계법령에서 정한 일정한 기간 동안 회원정보를 보관합니다.<br><br>\r\n");
      out.write("                           - 보존 항목 : 표시·광고에 관한 기록<br>\r\n");
      out.write("                           - 보존 근거 : 전자상거래등에서의 소비자보호에 관한 법률<br>\r\n");
      out.write("                           - 보존 기간 : 6개월<br><br>\r\n");
      out.write("               \r\n");
      out.write("                           - 보존 항목 : 계약 또는 청약철회 등에 관한 기록<br>\r\n");
      out.write("                           - 보존 근거 : 전자상거래등에서의 소비자보호에 관한 법률<br>\r\n");
      out.write("                           - 보존 기간 : 5년<br><br>\r\n");
      out.write("               \r\n");
      out.write("                           - 보존 항목 : 대금 결제 및 재화 등의 공급에 관한 기록<br>\r\n");
      out.write("                           - 보존 근거 : 전자상거래등에서의 소비자보호에 관한 법률<br>\r\n");
      out.write("                           - 보존 기간 : 5년<br><br>\r\n");
      out.write("               \r\n");
      out.write("                           - 보존 항목 : 소비자의 불만 또는 분쟁처리에 관한 기록<br>\r\n");
      out.write("                           - 보존 근거 : 전자상거래등에서의 소비자보호에 관한 법률<br>\r\n");
      out.write("                           - 보존 기간 : 3년<br><br>\r\n");
      out.write("               \r\n");
      out.write("                           - 보존 항목 : 로그기록자료, 접속지의 추적자료<br>\r\n");
      out.write("                           - 보존 근거 : 통신비밀보호법<br>\r\n");
      out.write("                           - 보존 기간 : 3개월<br><br>\r\n");
      out.write("                        </dd>\r\n");
      out.write("                        <dt class=\"b\">지금 탈퇴 하시면 가입일 기준 최대 30일 이후에 재 가입이 가능합니다.</dt>\r\n");
      out.write("                        <dd>(아이디가 여러 개인 경우 최종 가입 아이디 가입일 기준)<br>- 탈퇴한 아이디는 본인과 타인 모두 재사용 및 복구가 불가하오니 신중하게 선택하시기 바랍니다.</dd>\r\n");
      out.write("                     </dl>\r\n");
      out.write("               </div> <br>\r\n");
      out.write("               <form action=\"member_delete\">\r\n");
      out.write("               <div class=\"btn_m\">\r\n");
      out.write("                  <input type=\"submit\" class=\"btn-check\" value=\"탈퇴\" onclick=\"delete_confirm()\"> &nbsp;\r\n");
      out.write("                  <input type=\"reset\" class=\"btn-check\" value=\"취소\">\r\n");
      out.write("               </div>\r\n");
      out.write("               </form>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- footer section-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--   hm |  footer section-->\r\n");
      out.write("<footer class=\"ht-footer\">\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("      <div class=\"ft-copyright\">\r\n");
      out.write("         <div class=\"ft-left\">\r\n");
      out.write("            <p>© 2019 Bit 2 Jo. All Rights Reserved.</p>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"backtotop\">\r\n");
      out.write("            <p>\r\n");
      out.write("               <a href=\"#\" id=\"back-to-top\">맨 위로 <i\r\n");
      out.write("                  class=\"ion-ios-arrow-thin-up\"></i></a>\r\n");
      out.write("            </p>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!--   hm |  end of footer section-->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<button onclick=\"topFunction()\" id=\"hm_myBtn\" title=\"Go to top\">Top</button>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/mypage/../header1.jsp(33,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/css/plugins.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/mypage/../header1.jsp(35,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/resources/css/header_style.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/mypage/../header1.jsp(37,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/resources/css/hm_css.css");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                     ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("                     ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/mypage/../header2.jsp(513,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty m_email }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <li class=\"dropdown first\"><a\r\n");
          out.write("                           class=\"btn btn-default dropdown-toggle lv1\" href=\"mmlList\">\r\n");
          out.write("                              나영리 </a></li>\r\n");
          out.write("\r\n");
          out.write("                        <li><a href=\"mypage\">마이페이지</a></li>\r\n");
          out.write("                        <li><a href=\"Logout\">로그아웃</a></li>\r\n");
          out.write("                        <!--  hm |   <li><a href=\"member_join.html\">회원가입</a></li> -->\r\n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <li class=\"loginLink\"><a href=\"#\">로그인</a></li>\r\n");
          out.write("                        <li class=\"btn signupLink\"><a href=\"#\">회원가입</a></li>\r\n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/mypage/../header2.jsp(540,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/resources/js/jquery.js");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/mypage/../header2.jsp(542,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/resources/js/plugins.js");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/mypage/../header2.jsp(543,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/resources/js/plugins2.js");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /WEB-INF/mypage/member_out.jsp(28,32) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/resources/css/hjs.css");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /WEB-INF/mypage/../footer2.jsp(5,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/resources/js/header_custom.js");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /WEB-INF/mypage/../footer2.jsp(6,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/resources/js/hm_js.js");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }
}
