/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-07-25 08:19:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.board.share;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardShareList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/D:/phm_fork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MovieProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/header1.jsp", Long.valueOf(1563929061217L));
    _jspx_dependants.put("/WEB-INF/header2.jsp", Long.valueOf(1563934563164L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1562741737717L));
    _jspx_dependants.put("/WEB-INF/footer1.jsp", Long.valueOf(1563929061212L));
    _jspx_dependants.put("/WEB-INF/footer2.jsp", Long.valueOf(1563929061214L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 1. header1.jsp : head  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- header1 시작 -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if IE 7]>\r\n");
      out.write("<html class=\"ie ie7 no-js\" lang=\"en-US\">\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<!--[if IE 8]>\r\n");
      out.write("<html class=\"ie ie8 no-js\" lang=\"en-US\">\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<!--[if !(IE 7) | !(IE 8)  ]><!-->\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Basic need -->\r\n");
      out.write("<title>BlockBuster</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<link rel=\"profile\" href=\"#\">\r\n");
      out.write("\r\n");
      out.write("<!--Google Font-->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref='http://fonts.googleapis.com/css?family=Dosis:400,700,500|Nunito:300,400,600' />\r\n");
      out.write("<!-- Mobile specific meta -->\r\n");
      out.write("<meta name=viewport content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"format-detection\" content=\"telephone-no\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS files -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<!-- hm | </head>  전까지 -->\r\n");
      out.write("<!--  하단에 css 링크 추가 -->\r\n");
      out.write("<!-- header1 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 해당 페이지의 커스텀 css 설정입니다. -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/ws_personal.css?Ver=4\">\r\n");
      out.write("<!-- 3. heaer2.jsp : header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<!-- header2 시작 -->\r\n");
      out.write("<!--  hm | </head> 부터 </header>까지 -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!--preloading-->\r\n");
      out.write("\t<div id=\"preloader\">\r\n");
      out.write("\t\t<img class=\"logo\" src=\"resources/images/logo1.png\" alt=\"\" width=\"119\"\r\n");
      out.write("\t\t\theight=\"58\">\r\n");
      out.write("\t\t<div id=\"status\">\r\n");
      out.write("\t\t\t<span></span> <span></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--end of preloading-->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ======================================================                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ================================================================== -->\r\n");
      out.write("\t<!--                                               hm |        모달 팝업 시작                                                  -->\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\t<!--                                            hm |         로그인 팝업 시작                                                  -->\r\n");
      out.write("\t<!-- 입력 폼 패턴 삭제 -->\r\n");
      out.write("\t<div class=\"login-wrapper\" id=\"login-content\">\r\n");
      out.write("\t\t<div class=\"login-content\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("\t\t\t<h3>Login</h3>\r\n");
      out.write("\t\t\t<form action=\"Login.do\" method=\"post\" name=\"LoginForm\">\r\n");
      out.write("\t\t\t\t<!-- action 변경 필요 -->\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<label for=\"email\"> <input type=\"text\" name=\"m_email\"\r\n");
      out.write("\t\t\t\t\t\tid=\"m_email\" placeholder=\"이메일을 입력하세요\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\tautocapitalize=\"off\" />\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<label for=\"password\"> <input type=\"password\"\r\n");
      out.write("\t\t\t\t\t\tname=\"m_password\" id=\"m_password\" placeholder=\"비밀번호를 입력하세요\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"required\" />\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"remember\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"idSaveCheck\" name=\"remember\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"Remember me\"><span>아이디 저장</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row hm_logtext\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" id=\"loginbtn\">Login</button>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn signupLink\" href=\"#\">회원가입 | </a> <a\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn idfindLink\" href=\"\">아이디 찾기 | </a> <a\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn pwfindLink\" href=\"\">비밀번호 찾기</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--    hm |                                                         로그인 폼 팝업 끝                                                 -->\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\t<!-- |   hm |                                                      아이디 찾기 팝업 시작                                              | -->\r\n");
      out.write("\t<div class=\"login-wrapper\" id=\"id-find-content\">\r\n");
      out.write("\t\t<!-- login-content 아이디 변경 -->\r\n");
      out.write("\t\t<div class=\"login-content\">\r\n");
      out.write("\t\t\t<!-- login-content 클래스 변경 X -->\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("\t\t\t<h3>아이디 찾기</h3>\r\n");
      out.write("\t\t\t<h6>등록된 휴대폰 번호로 찾기</h6>\r\n");
      out.write("\t\t\t<p>가입 당시 입력한 휴대전화 번호를 통해 아이디를 찾을 수 있습니다.</p>\r\n");
      out.write("\t\t\t<form method=\"post\" class=\"findIdClass\">\r\n");
      out.write("\t\t\t\t<!-- login.php 액션 변경 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<label for=\"username\"> <!-- username 라벨 이름 변경 --> 이름 <!-- 라벨 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"m_name\" id=\"id_username\" placeholder=\"이름\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"required\" autocapitalize=\"off\" /> <!-- name, id, placeholder 변경-->\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row phone\">\r\n");
      out.write("\t\t\t\t\t<label for=\"phone\"> <!-- password 라벨 이름 변경 --> 휴대전화</br> <!-- 라벨 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"m_phone1\" maxlength=\"3\" placeholder=\"\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"required\" /> - <input type=\"text\" name=\"m_phone2\"\r\n");
      out.write("\t\t\t\t\t\tmaxlength=\"4\" placeholder=\"\" required=\"required\" /> - <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"text\" name=\"m_phone3\" maxlength=\"4\" placeholder=\"\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"required\" /> <!-- name, id, placeholder 변경-->\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\" id=\"hm_logtext\">\r\n");
      out.write("\t\t\t\t\t<!-- <button type=\"submit\">확인</button>  버튼 이름 변경 -->\r\n");
      out.write("\t\t\t\t\t<button class=\"idokLink\" type=\"button\">확인</button>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn pwfindLink\" href=\"\">비밀번호 찾기</a>\r\n");
      out.write("\t\t\t\t\t<!-- 하단 링크 변경 -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- |        hm |                                                  아이디 찾기 팝업 끝                                              |  -->\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\t<!-- |        hm |                                            아이디 찾기 확인 팝업 시작                                              | -->\r\n");
      out.write("\t<div class=\"login-wrapper\" id=\"id-ok-content\">\r\n");
      out.write("\t\t<!-- login-content 아이디 변경 -->\r\n");
      out.write("\t\t<div class=\"login-content\" style=\"text-align: center\">\r\n");
      out.write("\t\t\t<!-- login-content 클래스 변경 X -->\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("\t\t\t<!--  \r\n");
      out.write("            <h6 class=\"h6one\"> 입력하신 정보와 일치하는 아이디는 <br>아래와 같습니다.</h6>\r\n");
      out.write("\t\t\t<h6 class=\"h6two\"style=\"display:none\"> 입력하신 정보와 일치하는 <br>아이디가 없습니다.</h6>\r\n");
      out.write("\t\t\t-->\r\n");
      out.write("\t\t\t<!-- 이메일 정보 추가 -->\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span> </span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<button class=\"close\" type=\"button\" style=\"display: inline-block;\">확인</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- |           hm |                                          아이디 찾기 확인 팝업 끝                                              |  -->\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\t<!-- |          hm |                                        비밀번호 찾기 폼 팝업 시작                                              | -->\r\n");
      out.write("\t<div class=\"login-wrapper\" id=\"pw-find-content\">\r\n");
      out.write("\t\t<!-- login-content 아이디 변경 -->\r\n");
      out.write("\t\t<div class=\"login-content\">\r\n");
      out.write("\t\t\t<!-- login-content 클래스 변경 X -->\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("\t\t\t<h3>비밀번호 찾기</h3>\r\n");
      out.write("\t\t\t<h6>등록된 휴대폰 번호로 찾기</h6>\r\n");
      out.write("\t\t\t<p>가입 당시 입력한 휴대전화 번호를 통해 인증 후 새비밀번호를 등록해주세요.</p>\r\n");
      out.write("\t\t\t<form method=\"post\" class=\"findPwClass\">\r\n");
      out.write("\t\t\t\t<!-- login.php 액션 변경 -->\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<label for=\"email\"> <!-- username 라벨 이름 변경 --> 이메일 <!-- 라벨 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"m_email\" id=\"pw_email\" placeholder=\"이메일\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"required\" autocapitalize=\"off\" /> <!-- name, id, placeholder 변경-->\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<label for=\"username\"> <!-- username 라벨 이름 변경 --> 이름 <!-- 라벨 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"m_name\" id=\"pw_username\" placeholder=\"이름\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"required\" autocapitalize=\"off\" /> <!-- name, id, placeholder 변경-->\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row phone\">\r\n");
      out.write("\t\t\t\t\t<label for=\"phone\"> <!-- password 라벨 이름 변경 --> 휴대전화</br> <!-- 라벨 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<!-- 라벨 추가 --> <input type=\"text\" name=\"m_phone1\" maxlength=\"3\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"\" required=\"required\" /> - <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tname=\"m_phone2\" maxlength=\"4\" placeholder=\"\" required=\"required\" />\r\n");
      out.write("\t\t\t\t\t\t- <input type=\"text\" name=\"m_phone3\" maxlength=\"4\" placeholder=\"\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"required\" /> <!-- name, id, placeholder 변경-->\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\" id=\"hm_logtext\">\r\n");
      out.write("\t\t\t\t\t<!-- <button type=\"submit\">확인</button>  버튼 이름 변경 -->\r\n");
      out.write("\t\t\t\t\t<button class=\"pwokLink\" type=\"button\">확인</button>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn idfindLink\" href=\"\">아이디 찾기</a>\r\n");
      out.write("\t\t\t\t\t<!-- 하단 링크 변경 -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- |      hm |                                            비밀번호 찾기 폼 팝업 끝                                               |  -->\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\t<!-- |       hm |                                           비밀번호 찾기 확인 팝업 시작                                              | -->\r\n");
      out.write("\t<div class=\"login-wrapper\" id=\"pw-ok-content\">\r\n");
      out.write("\t\t<!-- login-content 아이디 변경 -->\r\n");
      out.write("\t\t<div class=\"login-content\">\r\n");
      out.write("\t\t\t<!-- login-content 클래스 변경 X -->\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("\t\t\t<h3>비밀번호 찾기</h3>\r\n");
      out.write("\t\t\t<p>회원님의 계정 비밀번호를 재설정 해주세요.</p>\r\n");
      out.write("\t\t\t<p>신규비밀번호는 8-20자 이내의 영문자, 숫자의 조합으로 작성 하셔야 합니다.</p>\r\n");
      out.write("\t\t\t<form class=\"newPassword\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"phone_number\" name=\"m_phone\" value=\"\" />\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<label for=\"password\"> <!-- username 라벨 이름 변경 --> 신규 비밀번호\r\n");
      out.write("\t\t\t\t\t\t입력 </br> <!-- 라벨 추가 --> <input type=\"password\" name=\"m_password\"\r\n");
      out.write("\t\t\t\t\t\tid=\"password\" placeholder=\"\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\tautocapitalize=\"off\" onchange=\"checkPassword(this.value)\" /> <!-- name, id, placeholder 변경-->\r\n");
      out.write("\t\t\t\t\t\t<span> </span>\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<label for=\"password2\"> <!-- username 라벨 이름 변경 --> 비밀번호 확인\r\n");
      out.write("\t\t\t\t\t\t</br> <!-- 라벨 추가 --> <input type=\"password\" name=\"m_password2\"\r\n");
      out.write("\t\t\t\t\t\tid=\"password2\" placeholder=\"\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\tautocapitalize=\"off\" onchange=\"checkPasswordConfirm(this.value)\" />\r\n");
      out.write("\t\t\t\t\t\t<!-- name, id, placeholder 변경--> <span> </span>\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"alert-success\" id=\"alert-success\">비밀번호가 일치합니다.</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"alert-danger\" id=\"alert-danger\">비밀번호가 일치하지 않습니다.</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<button class=\"pwcfLink\" type=\"button\">비밀번호 변경</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- |     hm |                                             비밀번호 찾기 확인 팝업 끝                                               |  -->\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\t<!--         hm |                                                   회원가입 폼 팝업 시작                                              -->\r\n");
      out.write("\t<!--signup form popup-->\r\n");
      out.write("\t<div class=\"login-wrapper\" id=\"signup-content\">\r\n");
      out.write("\t\t<div class=\"login-content\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("\t\t\t<h3>sign up</h3>\r\n");
      out.write("\t\t\t<form method=\"post\" id=\"joinform\" action=\"memberJoin.do\"\r\n");
      out.write("\t\t\t\tmethod=\"post\" onsubmit=\"return ws_check()\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<label for=\"email-2\"> 이메일 :</br> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tname=\"m_email\" id=\"email-2\" placeholder=\"이메일을 입력하세요\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"required\" />\r\n");
      out.write("\t\t\t\t\t\t<button class=\"overch\" id=\"email_overlap_chk\">중복확인</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t<div id=\"email_chk_msg\">이메일 중복검사를 눌러주세요</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<label for=\"username-2\"> 이름 : <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tname=\"m_name\" id=\"username-2\" placeholder=\"이름을 입력하세요\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"required\" />\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<label for=\"nickname-2\"> 닉네임 :</br> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tname=\"m_nickname\" id=\"nickname-2\" placeholder=\"닉네임을 입력하세요\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"required\" />\r\n");
      out.write("\t\t\t\t\t\t<button class=\"overch\" id=\"nick_overlap_chk\">중복확인</button>\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t<div id=\"nick_chk_msg\">닉네임 중복검사를 눌러주세요</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<label for=\"password-2\"> 비밀번호: <input type=\"password\"\r\n");
      out.write("\t\t\t\t\t\tname=\"m_password\" id=\"password-2\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"8-20자 이내 영문자, 숫자의 조합\" required=\"required\" />\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<label for=\"repassword-2\"> 비밀번호 확인 : <input type=\"password\"\r\n");
      out.write("\t\t\t\t\t\tname=\"password\" id=\"repassword-2\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"8-20자 이내 영문자, 숫자의 조합\" Srequired=\"required\" />\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row phone\">\r\n");
      out.write("\t\t\t\t\t<label for=\"repassword-2\"> 휴대전화 : </br> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tname=\"m_phone1\" placeholder=\"\" Srequired=\"required\" /> - <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"text\" name=\"m_phone2\" placeholder=\"\" Srequired=\"required\" />\r\n");
      out.write("\t\t\t\t\t\t- <input type=\"text\" name=\"m_phone3\" placeholder=\"\"\r\n");
      out.write("\t\t\t\t\t\tSrequired=\"required\" />\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<label for=\"genre-2\"> 선호장르 : </br> <label\r\n");
      out.write("\t\t\t\t\t\tclass=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("\t\t\t\t\t\t\tname=\"m_favorite\" value=\"공포/호러\" type=\"radio\" checked><span><i></i>공포/호러</span>\r\n");
      out.write("\t\t\t\t\t</label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("\t\t\t\t\t\t\tname=\"gender4\" value=\"멜로/로맨스\" type=\"radio\"><span><i></i>멜로/로맨스\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("\t\t\t\t\t\t\tname=\"m_favorite\" value=\"액션\" type=\"radio\"><span><i></i>액션</span>\r\n");
      out.write("\t\t\t\t\t</label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("\t\t\t\t\t\t\tname=\"m_favorite\" value=\"코미디\" type=\"radio\"><span><i></i>코미디</span>\r\n");
      out.write("\t\t\t\t\t</label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("\t\t\t\t\t\t\tname=\"m_favorite\" value=\"범죄\" type=\"radio\"><span><i></i>범죄</span>\r\n");
      out.write("\t\t\t\t\t</label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("\t\t\t\t\t\t\tname=\"m_favorite\" value=\"스릴러\" type=\"radio\"><span><i></i>스릴러</span>\r\n");
      out.write("\t\t\t\t\t</label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("\t\t\t\t\t\t\tname=\"m_favorite\" value=\"느와르\" type=\"radio\"><span><i></i>느와르</span>\r\n");
      out.write("\t\t\t\t\t</label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("\t\t\t\t\t\t\tname=\"m_favorite\" value=\"가족\" type=\"radio\"><span><i></i>가족</span>\r\n");
      out.write("\t\t\t\t\t</label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("\t\t\t\t\t\t\tname=\"m_favorite\" value=\"애니메이션\" type=\"radio\"><span><i></i>애니메이션</span>\r\n");
      out.write("\t\t\t\t\t</label> <label class=\"fancy-radio custom-color-coral\"> <input\r\n");
      out.write("\t\t\t\t\t\t\tname=\"m_favorite\" value=\"코미디\" type=\"radio\"><span><i></i>코미디</span>\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<label for=\"terms-2\"> 약관동의 : </br> <label\r\n");
      out.write("\t\t\t\t\t\tclass=\"fancy-checkbox custom-bgcolor-coral\"> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"checkbox\" checked name=\"useage_agree\" value=\"usage_ok\"><span>[필수]이용약관</span>\r\n");
      out.write("\t\t\t\t\t</label> <a class=\"termsLink\">약관보기</a> <label\r\n");
      out.write("\t\t\t\t\t\tclass=\"fancy-checkbox custom-bgcolor-coral\"> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"checkbox\" checked name=\"info_agree\" value=\"info_ok\"><span>[필수]개인정보\r\n");
      out.write("\t\t\t\t\t\t\t\t수집 및 이용</span>\r\n");
      out.write("\t\t\t\t\t</label> <a class=\"termsLink\">약관보기</a> <input name=\"m_cert\" type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"Y\" /> <label class=\"fancy-checkbox custom-bgcolor-coral\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" checked name=\"m_eagree\" value=\"Y\"><span>이메일\r\n");
      out.write("\t\t\t\t\t\t\t\t수신 동의</span>\r\n");
      out.write("\t\t\t\t\t</label> <label class=\"fancy-checkbox custom-bgcolor-coral\"> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"checkbox\" checked name=\"m_sagree\" value=\"Y\"><span>SMS\r\n");
      out.write("\t\t\t\t\t\t\t\t수신 동의</span>\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</label> <label class=\"fancy-checkbox custom-bgcolor-coral\" id=\"checkall\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" checked><span>전체동의</span>\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<button class=\"signupokLink\" type=\"submit\">가입하기</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--end of signup form popup-->\r\n");
      out.write("\t<!--        hm |                                                     회원가입 폼 팝업 끝                                               -->\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\t<!-- |      hm |                                              회원가입 확인 팝업 시작                                                 | -->\r\n");
      out.write("\t<!--signup OK popup-->\r\n");
      out.write("\t<div class=\"login-wrapper\" id=\"signup-ok-content\" style=\"height: 50%;\">\r\n");
      out.write("\t\t<div class=\"login-content\">\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("\t\t\t<h3>sign up</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h4>회원가입이 완료되었습니다.</h4>\r\n");
      out.write("\t\t\t</br>\r\n");
      out.write("\t\t\t<!-- 코드수정: id 넣어야 함-->\r\n");
      out.write("\t\t\t<h6>회원님 회원가입을 축하합니다.</h6>\r\n");
      out.write("\t\t\t</br>\r\n");
      out.write("\t\t\t<p>블록버스터의 다양한 영화 정보를 확인하세요!</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<button class=\"close\" type=\"submit\" id=\"hm_button2\">홈으로</button>\r\n");
      out.write("\t\t\t\t<button class=\"loginLink\" type=\"submit\" id=\"hm_button2\">로그인</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--end of signup OK popup-->\r\n");
      out.write("\t<!-- |          hm |                                           회원가입 확인 팝업 끝                                                 |  -->\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\t<!-- |          hm |                                          아이디 중복확인 팝업 시작                                               | -->\r\n");
      out.write("\t<div class=\"login-wrapper\" id=\"id-check-content\">\r\n");
      out.write("\t\t<!-- login-content 아이디 변경 -->\r\n");
      out.write("\t\t<div class=\"login-content\">\r\n");
      out.write("\t\t\t<!-- login-content 클래스 변경 X -->\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("\t\t\t<h3>아이디 중복 확인</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<label for=\"email\"> <!-- username 라벨 이름 변경 --> 사용할 이메일 입력 <!-- 라벨 추가 -->\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"email\" id=\"email\" placeholder=\"\"\r\n");
      out.write("\t\t\t\t\trequired=\"required\" autocapitalize=\"off\" /> <!-- name, id, placeholder 변경-->\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<button class=\"\" type=\"submit\">확인</button>\r\n");
      out.write("\t\t\t\t<!-- 한칸만 끄기.. -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- |           hm |                                          아이디 중복확인 팝업 끝                                               |  -->\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\t<!-- |            hm |                                        닉네임 중복확인 팝업 시작                                               | -->\r\n");
      out.write("\t<div class=\"login-wrapper\" id=\"nik-check-content\">\r\n");
      out.write("\t\t<!-- login-content 아이디 변경 -->\r\n");
      out.write("\t\t<div class=\"login-content\">\r\n");
      out.write("\t\t\t<!-- login-content 클래스 변경 X -->\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("\t\t\t<h3>닉네임 중복 확인</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<label for=\"nickname\"> <!-- username 라벨 이름 변경 --> 사용할 닉네임 입력\r\n");
      out.write("\t\t\t\t\t<!-- 라벨 추가 --> <input type=\"text\" name=\"nickname\" id=\"nickname\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"\" required=\"required\" autocapitalize=\"off\" /> <!-- name, id, placeholder 변경-->\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<button class=\"\" type=\"submit\">확인</button>\r\n");
      out.write("\t\t\t\t<!-- 한칸만 끄기 -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- |      hm |                                               닉네임 중복확인 팝업 끝                                               |  -->\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\t<!-- |            hm |                                        약관 팝업 시작                                               | -->\r\n");
      out.write("\t<div class=\"login-wrapper2\" id=\"terms-content\">\r\n");
      out.write("\t\t<!-- login-content 아이디 변경 -->\r\n");
      out.write("\t\t<div class=\"login-content2\">\r\n");
      out.write("\t\t\t<!-- login-content 클래스 변경 X -->\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("\t\t\t<h3>약관</h3>\r\n");
      out.write("\t\t\t<div class=\"hm_contents\">\r\n");
      out.write("\t\t\t\t<h3>제 1장 총칙</h3>\r\n");
      out.write("\t\t\t\t<h4>제 1 조 (목적)</h4>\r\n");
      out.write("\t\t\t\t<p>본 약관은 통계청(이하 ‘제공기관’이라 한다)에서 제공하는 BBB(Block Buster Bit)를 활용함에\r\n");
      out.write("\t\t\t\t\t있어 준수하여야 하는 활용조건 및 절차, 활용자의 권리・의무 및 책임사항, 기타 필요한 사항을 규정함을 목적으로 합니다.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<!-- <button onclick=\"this.parentNode.parentsNode.style.display = 'none';\">확인</button>-->\r\n");
      out.write("\t\t\t\t<button class=\"terms-content-bt\">닫기</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- |      hm |                                               약관 팝업 끝                                               |  -->\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\t<!--        hm |                                                       모달 팝업 끝                                                    -->\r\n");
      out.write("\t<!-- ======================================================================================================================== -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- BEGIN | Header -->\r\n");
      out.write("\t<header class=\"ht-header sticky\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<nav class=\"navbar navbar-default navbar-custom\">\r\n");
      out.write("\t\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header logo\">\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\t\tdata-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"nav-icon1\">\r\n");
      out.write("\t\t\t\t\t\t\t<span></span> <span></span> <span></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<a href=\"index.do\"><img class=\"logo\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"resources/images/logo1.png\" alt=\"\" width=\"119\" height=\"58\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse flex-parent\"\r\n");
      out.write("\t\t\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav flex-child-menu menu-left\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"hidden\"><a href=\"#page-top\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t<!--  hm |   add : 각 항목의 텍스트 변경-->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown first\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-default dropdown-toggle lv1\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"movieTicketing.html\"> 예매 </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown first\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-default dropdown-toggle lv1\" href=\"movieList.html\">\r\n");
      out.write("\t\t\t\t\t\t\t\t영화 </a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown first\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-default dropdown-toggle lv1\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"cinemaList.html\"> 영화관 </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown first\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-default dropdown-toggle lv1\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"boardEventCollection.html\"> 이벤트 & 정보 </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown first\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-default dropdown-toggle lv1\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"dropdown\" data-hover=\"dropdown\"> 커뮤니티<i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-angle-down\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu level1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"boardFreeList.do\">자유 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"it-last\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"boardShareList.do\">나눔 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav flex-child-menu menu-right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 검색 모달 -->\r\n");
      out.write("\t\t\t\t<form id=\"demo-2\">\r\n");
      out.write("\t\t\t\t\t<input type=\"search\" placeholder=\"Search\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- END | Header -->\r\n");
      out.write("\t<script src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("\t<script src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("\t<script src=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- header2 끝 -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  \r\n");
      out.write("* @Class Name : EgovSampleService.java\r\n");
      out.write("* @Description : EgovSampleService Class\r\n");
      out.write("* @Modification Information\r\n");
      out.write("* @\r\n");
      out.write("* @  수정일      \t\t\t수정자 \t\t\t\t             수정내용\r\n");
      out.write("* @ ---------   ---------   -------------------------------\r\n");
      out.write("* @ 2019.07.2     이웅식                    \t\t\t최초 생성\r\n");
      out.write("* @ 2019.07.22     한유진    \t header, footer 수정(1,2 버전으로 변경)\r\n");
      out.write("*\r\n");
      out.write("* @author BIT 116기 2조\r\n");
      out.write("* @since 2019. 07.01\r\n");
      out.write("* @version 1.0\r\n");
      out.write("* @see\r\n");
      out.write("*\r\n");
      out.write("*  Copyright (C) by bit 2조 All right reserved.\r\n");
      out.write("*/-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"hero common-hero\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<div class=\"hero-ct\">\r\n");
      out.write("\t\t\t\t\t<h1> 나눔 게시판</h1>\r\n");
      out.write("\t\t\t\t\t<ul class=\"breadcumb\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"#\">커뮤니티</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li> <span class=\"ion-ios-arrow-right\"></span> 자유 게시판</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 컨텐츠 시작 -->\r\n");
      out.write("<div class=\"buster-light\">\r\n");
      out.write("\t<div class=\"movie-items\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"col-md-14\">\r\n");
      out.write("\t\t\t<!-- 1. listTable 배치 -->\r\n");
      out.write("\t\t\t<h4>나눔 게시판 </h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<!-- listTable 배치 시작 -->\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<div style=\"position:relative;top:50px\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"ws-btn-reddish-write\" value=\"글쓰기\" onClick=\"location.href='boardShareWrite.do'\"><i class=\"fa fa-pencil\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t<!-- 1. listTable 배치 -->\r\n");
      out.write("\t\t\t\t\t\t<table class=\"ws_table\">\r\n");
      out.write("\t\t\t\t\t\t  <thead>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 2. 최초의 행. 열의 종류 구분 -->\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t  <th style=\"width:8%;\">글번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t  <th style=\"width:7%;\">카테고리</th>\r\n");
      out.write("\t\t\t\t\t\t\t  <th style=\"width:45%;\">제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t  <th style=\"width:10%;\">글쓴이</th>\r\n");
      out.write("\t\t\t\t\t\t\t  <th style=\"width:10%;\">최근수정일</th>\r\n");
      out.write("\t\t\t\t\t\t\t  <th style=\"width:10%;\">조회수</th>\r\n");
      out.write("\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t  </thead>\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t <!-- 향후 core jstl의 foreach로 게시글의 목록이 올 자리다 -->\r\n");
      out.write("\t\t\t\t\t\t  <tbody>\r\n");
      out.write("\t\t\t\t\t\t   <!-- 3. 공지사항. strong으로 강조를 주며, 게시자의 아이디가 다홍색으로 처리된다. 항상 최상단 노출-->\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"notice\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td><strong>0026</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td><strong>공지</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td><strong>비속어 사용과 음란물 게시시 활동정지 처분합니다.</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td ><strong>admin01</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td ><strong>2011/04/25</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td><strong>84200</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"notice\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td><strong>002</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td><strong>공지</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td><strong>정치글은 글삭제 대상입니다.</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td><strong>admin01</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td><strong>2011/07/25</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td><strong>16847</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<!--4.  자유게시판 게시글의 나열 시작 -->\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td >0024</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>결말해석</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>고질라 쿠키영상 무슨뜻인가요?</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>가모라</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2009/01/12</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2400</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td>0023</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>잡담</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>Edinburgh</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>22</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2012/03/29</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>$433,060</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td>0022</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>토론</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>Tokyo</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>33</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2008/11/28</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>$162,700</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td>0020</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>잡담해석</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>New York</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>61</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2012/12/02</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>$372,000</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td>0019</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>잡담</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>San Francisco</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>59</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2012/08/06</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>$137,500</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td>0017</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>유머</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>Tokyo</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>55</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2010/10/14</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>$327,900</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td>0016</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>토론</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>San Francisco [13]</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>39</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2009/09/15</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>$205,500</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td>0015</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>결말해석</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>Edinburgh [13]</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>23</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2008/12/13</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>$103,600</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td>0014</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>결말해석</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>London</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>30</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2008/12/19</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>$90,560</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td>00013</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>유머</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>Edinburgh</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>22</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2013/03/03</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>$342,000</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td>00013</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>유머</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>Edinburgh</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>22</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2013/03/03</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>$342,000</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td>0014</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>결말해석</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>London</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>30</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2008/12/19</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>$90,560</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td>00013</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>유머</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>Edinburgh</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>22</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2013/03/03</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>$342,000</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td>00013</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>유머</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>Edinburgh</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>22</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2013/03/03</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>$342,000</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td>0014</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>결말해석</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>London</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>30</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2008/12/19</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>$90,560</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td>00013</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>유머</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>Edinburgh</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>22</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2013/03/03</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>$342,000</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t  <td>00013</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>유머</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>Edinburgh</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>22</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>2013/03/03</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>$342,000</td>\r\n");
      out.write("\t\t\t\t\t\t\t  <td>모바일 글제목. </td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t  </tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t  <!--TableList의 끝-->\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t <!--5. 검색바  구현부  -->\r\n");
      out.write("\t\t\t\t\t<center class=\"col-md-14\">\r\n");
      out.write("\t\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"all\">전체</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"ticket\">결말해석</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"snack\">유머</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"snack\">잡담</option>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"united\">제목</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"saab\">글쓴이</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"saab\">전체</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t<input class=\"list-search\" type=\"text\" placeholder=\"원하시는 내용을 입력하세요\">\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t<button class=\"ws-btn-reddish-search\"><i class=\"fa fa-search\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 6. 페이징 : 그대로 따옴 기초 탬플릿의 [ bloglist_ligth.html]  -->\r\n");
      out.write("            \t<ul class=\"pagination\">\r\n");
      out.write("            \t\t<li class=\"icon-prev\"><a href=\"#\"><i class=\"ion-ios-arrow-left\"></i></a></li>\r\n");
      out.write("            \t\t<li class=\"active\"><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">...</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">21</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">22</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"icon-next\"><a href=\"#\"><i class=\"ion-ios-arrow-right\"></i></a></li>\r\n");
      out.write("            \t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("<!--list 페이지 구현의 몸통부 끝. 이하 footer 등-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 5. footer1.jsp : footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--   hm |  footer section-->\r\n");
      out.write("<footer class=\"ht-footer\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"flex-parent-ft\">\r\n");
      out.write("\t\t\t<div class=\"flex-child-ft item1\">\r\n");
      out.write("\t\t\t\t<a href=\"index.do\"><img class=\"logo\"\r\n");
      out.write("\t\t\t\t\tsrc=\"resources/images/logo1.png\" alt=\"\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"flex-child-ft item2\">\r\n");
      out.write("\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t<a href=\"faq_list.html\"> 고객센터 </a>\r\n");
      out.write("\t\t\t\t</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<h4>\r\n");
      out.write("\t\t\t\t<a class=\"termsLink\"> 약관보기 </a>\r\n");
      out.write("\t\t\t</h4>\r\n");
      out.write("\t\t\t<div class=\"flex-child-ft item3\">\r\n");
      out.write("\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t<a href=\"one_regist.do\"> 1:1 문의 </a>\r\n");
      out.write("\t\t\t\t</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"flex-child-ft item4\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"ft-copyright\">\r\n");
      out.write("\t\t\t<div class=\"ft-left\">\r\n");
      out.write("\t\t\t\t<p>© 2019 Bit 2 Jo. All Rights Reserved.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"backtotop\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" id=\"back-to-top\">맨 위로 <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"ion-ios-arrow-thin-up\"></i></a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!--   hm |  end of footer section-->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<button onclick=\"topFunction()\" id=\"hm_myBtn\" title=\"Go to top\">Top</button>\r\n");
      out.write("\r\n");
      out.write("<!-- 6. 페이지별 script 추가 -->\t\r\n");
      out.write("<!-- footer2.jsp : script -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/header1.jsp(33,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/css/plugins.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/header1.jsp(35,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/resources/css/header_style.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/header1.jsp(37,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/resources/css/hm_css.css");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/header2.jsp(510,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty m_email }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<li class=\"dropdown first\"><a\r\n");
          out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-default dropdown-toggle lv1\" href=\"mmlList.do\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t나영리 </a></li>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><a href=\"mypage.do\">마이페이지</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><a href=\"Logout.do\">로그아웃</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<!--  hm |   <li><a href=\"member_join.html\">회원가입</a></li> -->\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<li class=\"loginLink\"><a href=\"#\">로그인</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li class=\"btn signupLink\"><a href=\"#\">회원가입</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/header2.jsp(537,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/resources/js/jquery.js");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/header2.jsp(538,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/resources/js/plugins.js");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/header2.jsp(539,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/resources/js/plugins2.js");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /WEB-INF/footer2.jsp(8,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/resources/js/header_custom.js");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /WEB-INF/footer2.jsp(9,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/resources/js/hm_js.js");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }
}
