/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-08-01 06:25:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.event;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cinemaList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/project_bbb/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MovieProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1564550655296L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if IE 7]>\r\n");
      out.write("<html class=\"ie ie7 no-js\" lang=\"en-US\">\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<!--[if IE 8]>\r\n");
      out.write("<html class=\"ie ie8 no-js\" lang=\"en-US\">\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<!--[if !(IE 7) | !(IE 8)  ]><!-->\r\n");
      out.write("<html lang=\"en\" class=\"no-js\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<!-- Basic need -->\r\n");
      out.write("\t<title>이벤트창</title>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"\">\r\n");
      out.write("\t<meta name=\"author\" content=\"\">\r\n");
      out.write("\t<link rel=\"profile\" href=\"#\">\r\n");
      out.write("\r\n");
      out.write("    <!--Google Font-->\r\n");
      out.write("    <link rel=\"stylesheet\" href='http://fonts.googleapis.com/css?family=Dosis:400,700,500|Nunito:300,400,600' />\r\n");
      out.write("\t<!-- Mobile specific meta -->\r\n");
      out.write("\t<meta name=viewport content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<meta name=\"format-detection\" content=\"telephone-no\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- CSS files -->\r\n");
      out.write("\t<!-- c:url jstl 추가부분  -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 제이쿼리  -->\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\">\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t// 탭기능 \r\n");
      out.write("\t// tab menu\r\n");
      out.write("\t$(function () {\t\r\n");
      out.write("\ttab('#tab',0);\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction tab(e, num){\r\n");
      out.write("    var num = num || 0;\r\n");
      out.write("    var menu = $(e).children();\r\n");
      out.write("    var con = $(e+'_con').children();\r\n");
      out.write("    var select = $(menu).eq(num);\r\n");
      out.write("    var i = num;\r\n");
      out.write("\r\n");
      out.write("    select.addClass('on');\r\n");
      out.write("    con.eq(num).show();\r\n");
      out.write("\r\n");
      out.write("    menu.click(function(){\r\n");
      out.write("        if(select!==null){\r\n");
      out.write("            select.removeClass(\"on\");\r\n");
      out.write("            con.eq(i).hide();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        select = $(this);\t\r\n");
      out.write("        i = $(this).index();\r\n");
      out.write("\r\n");
      out.write("        select.addClass('on');\r\n");
      out.write("        con.eq(i).show();\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("//2번째\r\n");
      out.write("$(document).ready (function () {\r\n");
      out.write("    //탭(ul) onoff\r\n");
      out.write("    $('.jq_tabonoff>.jq_cont').children().css('display', 'none');\r\n");
      out.write("    $('.jq_tabonoff>.jq_cont div:first-child').css('display', 'block');\r\n");
      out.write("    $('.jq_tabonoff>.jq_tab li:first-child').addClass('on');\r\n");
      out.write("    $('.jq_tabonoff').delegate('.jq_tab>li', 'click', function() {\r\n");
      out.write("        var index = $(this).parent().children().index(this);\r\n");
      out.write("        $(this).siblings().removeClass();\r\n");
      out.write("        $(this).addClass('on');\r\n");
      out.write("        $(this).parent().next('.jq_cont').children().hide().eq(index).show();\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// 더보기 제이커리\r\n");
      out.write("$(window).on('load', function () {\r\n");
      out.write("    load('#js-load', '5');\r\n");
      out.write("    $(\"#js-btn-wrap .button\").on(\"click\", function () {\r\n");
      out.write("        load('#js-load', '5', '#js-btn-wrap');\r\n");
      out.write("    })\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("function load(id, cnt, btn) {\r\n");
      out.write("    var girls_list = id + \" .js-load:not(.active)\";\r\n");
      out.write("    var girls_length = $(girls_list).length;\r\n");
      out.write("    var girls_total_cnt;\r\n");
      out.write("    if (cnt < girls_length) {\r\n");
      out.write("        girls_total_cnt = cnt;\r\n");
      out.write("    } else {\r\n");
      out.write("        girls_total_cnt = girls_length;\r\n");
      out.write("        $('.button').hide()\r\n");
      out.write("    }\r\n");
      out.write("    $(girls_list + \":lt(\" + girls_total_cnt + \")\").addClass(\"active\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--preloading-->\r\n");
      out.write("<div id=\"preloader\">\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <img class=\"logo\" src=\"/resources/images/logo1.png\" alt=\"\" width=\"119\" height=\"58\">\r\n");
      out.write("    <div id=\"status\">\r\n");
      out.write("        <span></span>\r\n");
      out.write("        <span></span>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--end of preloading-->\r\n");
      out.write("<!--login form popup-->\r\n");
      out.write("<div class=\"login-wrapper\" id=\"login-content\">\r\n");
      out.write("    <div class=\"login-content\">\r\n");
      out.write("        <a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("        <h3>Login</h3>\r\n");
      out.write("        <form method=\"post\" action=\"login.php\">\r\n");
      out.write("        \t<div class=\"row\">\r\n");
      out.write("        \t\t <label for=\"username\">\r\n");
      out.write("                    Username:\r\n");
      out.write("                    <input type=\"text\" name=\"username\" id=\"username\" placeholder=\"Hugh Jackman\" pattern=\"^[a-zA-Z][a-zA-Z0-9-_\\.]{8,20}$\" required=\"required\" />\r\n");
      out.write("                </label>\r\n");
      out.write("        \t</div>\r\n");
      out.write("           \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("            \t<label for=\"password\">\r\n");
      out.write("                    Password:\r\n");
      out.write("                    <input type=\"password\" name=\"password\" id=\"password\" placeholder=\"******\" pattern=\"(?=^.{8,}$)((?=.*\\d)|(?=.*\\W+))(?![.\\n])(?=.*[A-Z])(?=.*[a-z]).*$\" required=\"required\" />\r\n");
      out.write("                </label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("            \t<div class=\"remember\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"remember\" value=\"Remember me\"><span>Remember me</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("            \t\t<a href=\"#\">Forget password ?</a>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            </div>\r\n");
      out.write("           <div class=\"row\">\r\n");
      out.write("           \t <button type=\"submit\">Login</button>\r\n");
      out.write("           </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        \t<p>Or via social</p>\r\n");
      out.write("            <div class=\"social-btn-2\">\r\n");
      out.write("            \t<a class=\"fb\" href=\"#\"><i class=\"ion-social-facebook\"></i>Facebook</a>\r\n");
      out.write("            \t<a class=\"tw\" href=\"#\"><i class=\"ion-social-twitter\"></i>twitter</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--end of login form popup-->\r\n");
      out.write("<!--signup form popup-->\r\n");
      out.write("<div class=\"login-wrapper\"  id=\"signup-content\">\r\n");
      out.write("    <div class=\"login-content\">\r\n");
      out.write("        <a href=\"#\" class=\"close\">x</a>\r\n");
      out.write("        <h3>sign up</h3>\r\n");
      out.write("        <form method=\"post\" action=\"signup.php\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                 <label for=\"username-2\">\r\n");
      out.write("                    Username:\r\n");
      out.write("                    <input type=\"text\" name=\"username\" id=\"username-2\" placeholder=\"Hugh Jackman\" pattern=\"^[a-zA-Z][a-zA-Z0-9-_\\.]{8,20}$\" required=\"required\" />\r\n");
      out.write("                </label>\r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <label for=\"email-2\">\r\n");
      out.write("                    your email:\r\n");
      out.write("                    <input type=\"password\" name=\"email\" id=\"email-2\" placeholder=\"\" pattern=\"(?=^.{8,}$)((?=.*\\d)|(?=.*\\W+))(?![.\\n])(?=.*[A-Z])(?=.*[a-z]).*$\" required=\"required\" />\r\n");
      out.write("                </label>\r\n");
      out.write("            </div>\r\n");
      out.write("             <div class=\"row\">\r\n");
      out.write("                <label for=\"password-2\">\r\n");
      out.write("                    Password:\r\n");
      out.write("                    <input type=\"password\" name=\"password\" id=\"password-2\" placeholder=\"\" pattern=\"(?=^.{8,}$)((?=.*\\d)|(?=.*\\W+))(?![.\\n])(?=.*[A-Z])(?=.*[a-z]).*$\" required=\"required\" />\r\n");
      out.write("                </label>\r\n");
      out.write("            </div>\r\n");
      out.write("             <div class=\"row\">\r\n");
      out.write("                <label for=\"repassword-2\">\r\n");
      out.write("                    re-type Password:\r\n");
      out.write("                    <input type=\"password\" name=\"password\" id=\"repassword-2\" placeholder=\"\" pattern=\"(?=^.{8,}$)((?=.*\\d)|(?=.*\\W+))(?![.\\n])(?=.*[A-Z])(?=.*[a-z]).*$\" required=\"required\" />\r\n");
      out.write("                </label>\r\n");
      out.write("            </div>\r\n");
      out.write("           <div class=\"row\">\r\n");
      out.write("             <button type=\"submit\">sign up</button>\r\n");
      out.write("           </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--end of signup form popup-->\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN | Header -->\r\n");
      out.write("<header class=\"ht-header\" style=\"position: relative;\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-default navbar-custom\">\r\n");
      out.write("\t\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header logo\">\r\n");
      out.write("\t\t\t\t    <div class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t\t    <div id=\"nav-icon1\">\r\n");
      out.write("\t\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    <a href=\"index.html\"><img class=\"logo\" src=\"/resources/images/logo1.png\" alt=\"\" width=\"119\" height=\"58\"></a>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse flex-parent\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav flex-child-menu menu-left\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#page-top\"></a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- add : 각 항목의 텍스트 변경-->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"btn btn-default dropdown-toggle lv1\" href=\"movieTicketing.html\">\r\n");
      out.write("\t\t\t\t\t\t\t\t예매\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"btn btn-default dropdown-toggle lv1\" data-toggle=\"dropdown\" data-hover=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t영화<i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu level1\">\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"movieChart.html\">영화 차트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"it-last\"><a href=\"movieList.html\">영화 목록</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"btn btn-default dropdown-toggle lv1\" href=\"cinemaList.html\">\r\n");
      out.write("\t\t\t\t\t\t\t\t영화관\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"btn btn-default dropdown-toggle lv1\" href=\"boardEventCollection.html\">\r\n");
      out.write("\t\t\t\t\t\t\t\t이벤트&정보\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"btn btn-default dropdown-toggle lv1\" data-toggle=\"dropdown\" data-hover=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t커뮤니티<i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu level1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"boardFreeList.html\">자유 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"it-last\"><a href=\"boardShreList.html\">나눔 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav flex-child-menu menu-right\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown first\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn btn-default dropdown-toggle lv1\" href=\"mmlList.html\">\r\n");
      out.write("\t\t\t\t\t\t\t나영리\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>                \r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"mypage.html\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"loginLink\"><a href=\"#\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"btn signupLink\"><a href=\"#\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.navbar-collapse -->\r\n");
      out.write("\t    </nav>\r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- END | Header -->\r\n");
      out.write("\r\n");
      out.write("<!-- Start | Section -->\r\n");
      out.write("<section class=\"section\">\r\n");
      out.write("<!-- 지역 영화관 선택 -->\t\r\n");
      out.write("<form class=\"cinema_select\" name=\"frm1\" >\r\n");
      out.write("<select name=\"gd_code\" size=\"3\" onChange=\"redirect(this.selectedIndex);\">\r\n");
      out.write("<option value=\"1\">CGV</option>\r\n");
      out.write("<option value=\"2\">롯데시네마</option>\r\n");
      out.write("<option value=\"3\">메가박스</option>\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("<select name=\"gp_color\" size=\"8\" onChange=\"redirect1(this.selectedIndex);\">\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("<select name=\"gp_face\" size=\"8\" onChange = \"redirect2(this.selectedIndex);\">\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("<select name=\"gp_quantity\" size=\"8\">\r\n");
      out.write("</select>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<!-- 영화관 정보 시작 -->\r\n");
      out.write("<div class=\"cinema_info\" style=\"\">\r\n");
      out.write("\t<div class=\"cinema_info_text\">\r\n");
      out.write("\t\t<span>CGV</span><span>서울 영화관1호</span><br>\r\n");
      out.write("\t\t<span>인천광역시 중구 운서동 3088-3 예스타워 영종 7층</span><br>\r\n");
      out.write("\t\t<a href=\"./www.naver.com\">홈페이지 이동</a><span>02-444-4444</span><span>|</span><span>상영관 수</span><span>전체 좌석</span>\r\n");
      out.write("\t\t<p style=\"float: right; background-color: #333; color: #fff; width: 120px;line-height: 80px; padding: 10px; margin-top: 30px; text-align: center; vertical-align: middle;\">예매정보</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"cinema_info_map\">\r\n");
      out.write("\t\t<img src=\"./images/.png\">지도\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 영화관 정보 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 극장 정보 탭  시작 -->\r\n");
      out.write("<div class=\"cinema_tab\">\r\n");
      out.write("\t<div class=\"tab-wrap\">\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li><a href=\"#tab1\">tab1</a></li>\r\n");
      out.write("        <li><a href=\"#tab2\">tab2</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <div>\r\n");
      out.write("        <article id=\"tab1\">\r\n");
      out.write("            <h1>극장정보</h1>\r\n");
      out.write("            <div class=\"cinema_traffic\">\r\n");
      out.write("            \t<div class=\"cinema_traffic_info\" style=\"\">\r\n");
      out.write("            \t\t<!-- 교통 / 주차 정보 데이터 -->\r\n");
      out.write("            \t\t<p>- 교통편</p>\r\n");
      out.write("            \t\t<p style=\"width: 1200px; height: 300px; border: 1px solid:#333;\">교통편 설명</p>\r\n");
      out.write("            \t\t<p>- 주차</p>\r\n");
      out.write("            \t\t<p style=\"width: 1200px; height: 300px; border: 1px solid:#333;\">교통편 설명</p>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </article>\r\n");
      out.write("        <article id=\"tab2\">\r\n");
      out.write("            <h1>리뷰</h1>\r\n");
      out.write("           \t<div class=\"cinema_review\">\r\n");
      out.write("           \t\t<div class=\"cinema_review_table\">\r\n");
      out.write("           \t\t\t<p>영화 리스트 넣으면됨~</p>\r\n");
      out.write("           \t\t</div>\r\n");
      out.write("           \t</div>\r\n");
      out.write("        </article>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 극장 정보 탭  끝 -->\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- END | Section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!--tabs end--> \r\n");
      out.write("<!-- footer section-->\r\n");
      out.write("<footer class=\"ht-footer\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"flex-parent-ft\">\r\n");
      out.write("\t\t\t<div class=\"flex-child-ft item1\">\r\n");
      out.write("\t\t\t\t <a href=\"index.html\"><img class=\"logo\" src=\"images/logo1.png\" alt=\"\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"flex-child-ft item2\">\r\n");
      out.write("\t\t\t\t<a href=\"faq_list.html\"><h4>고객센터 </h4></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"flex-child-ft item3\">\r\n");
      out.write("\t\t\t\t<a href=\"one_regist.html\"><h4>1:1 문의</h4></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"flex-child-ft item4\">\r\n");
      out.write("\t\t\t\t<h4></h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t<div class=\"ft-copyright\">\r\n");
      out.write("\t\t<div class=\"ft-left\">\r\n");
      out.write("\t\t\t<p>© 2019 Bit 2 Jo. All Rights Reserved.</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"backtotop\">\r\n");
      out.write("\t\t\t<p><a href=\"#\" id=\"back-to-top\">맨 위로  <i class=\"ion-ios-arrow-thin-up\"></i></a></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!--tabs end--> \r\n");
      out.write("<!-- footer section-->\r\n");
      out.write("\r\n");
      out.write("<!-- end of footer section-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- end of footer section-->\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"> -->\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- <script src=\"js/jquery.js\"></script>\r\n");
      out.write("<script src=\"js/plugins.js\"></script>\r\n");
      out.write("<script src=\"js/plugins2.js\"></script>\r\n");
      out.write("<script src=\"js/custom.js\"></script> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/event/cinemaList.jsp(30,30) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/css/style.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/event/cinemaList.jsp(31,30) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/resources/css/kgh_style.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/event/cinemaList.jsp(32,30) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/resources/css/plugins.css");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/event/cinemaList.jsp(396,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/resources/js/jquery.js");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/event/cinemaList.jsp(397,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/resources/js/jquery.js");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/event/cinemaList.jsp(398,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/resources/js/plugins.js");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /WEB-INF/event/cinemaList.jsp(399,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/resources/js/plugins2.js");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /WEB-INF/event/cinemaList.jsp(400,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/resources/js/custom.js");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }
}
